# -*- coding: utf-8 -*-
"""KeyBert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dU6AME3zXt8zIS4-7wizXIJU6myWieDI
"""

doc="Collaborative filtering leverages the power of community to provide recommendations.Collaborative filters are one of the most popular recommender models used in the industryand have found huge success for companies such as Amazon. Collaborative filtering can bebroadly classified into two types."

doc

pip install keybert[all]

from keybert import KeyBERT

kw_model = KeyBERT()
keywords = kw_model.extract_keywords(doc)

keywords

kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 1), stop_words=None)

kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 2), stop_words=None)

